# Generated by Django 4.2 on 2026-09-10 12:18

import dashboard.models
from decimal import Decimal
from django.conf import settings
import django.core.validators
from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='FeeRule',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('network', models.CharField(choices=[('MTN', 'MTN'), ('AIRTEL', 'Airtel')], max_length=10)),
                ('merchant_type', models.CharField(blank=True, choices=[('INDIVIDUAL', 'Individual Merchant'), ('BUSINESS', 'Business Merchant')], help_text='Leave blank for Airtel (band-based, merchant-type independent).', max_length=15, null=True)),
                ('min_amount', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=12)),
                ('max_amount', models.DecimalField(blank=True, decimal_places=2, help_text="Leave blank for 'and above'.", max_digits=12, null=True)),
                ('fee_type', models.CharField(choices=[('FIXED', 'Fixed amount (UGX)'), ('PERCENT', 'Percentage of amount')], max_length=10)),
                ('fee_value', models.DecimalField(decimal_places=2, help_text='UGX amount if FIXED, percentage points if PERCENT (e.g. 1.00 = 1%).', max_digits=10)),
                ('is_active', models.BooleanField(default=True)),
            ],
            options={
                'ordering': ['network', 'min_amount'],
            },
        ),
        migrations.CreateModel(
            name='Provider',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('merchant_code', models.CharField(db_index=True, max_length=20, unique=True)),
                ('name', models.CharField(max_length=255)),
                ('category', models.CharField(choices=[('CLINIC', 'Clinic'), ('PHARMACY', 'Pharmacy'), ('HOSPITAL', 'Hospital'), ('OTHER', 'Other Healthcare Provider')], max_length=20)),
                ('mobile_number', models.CharField(help_text='Registered mobile-money number, e.g. 256772123456', max_length=15)),
                ('network', models.CharField(choices=[('MTN', 'MTN'), ('AIRTEL', 'Airtel')], max_length=10)),
                ('merchant_type', models.CharField(choices=[('INDIVIDUAL', 'Individual Merchant'), ('BUSINESS', 'Business Merchant')], default='INDIVIDUAL', help_text='Only relevant for MTN fee-band lookup.', max_length=15)),
                ('commission_type', models.CharField(choices=[('FIXED', 'Fixed amount (UGX)'), ('PERCENT', 'Percentage of amount')], default='PERCENT', max_length=10)),
                ('commission_value', models.DecimalField(decimal_places=2, default=Decimal('0.00'), help_text="eDoctorUG's own commission: either UGX flat amount or percent, per commission_type.", max_digits=10)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('managed_by', models.ForeignKey(blank=True, help_text='Admin user who manages this provider in the dashboard (for scoping non-superuser access).', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='providers', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='Transaction',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('reference_id', models.UUIDField(default=uuid.uuid4, editable=False, unique=True)),
                ('payment_external_reference', models.CharField(max_length=64, unique=True)),
                ('msisdn', models.CharField(max_length=15)),
                ('network', models.CharField(choices=[('MTN', 'MTN'), ('AIRTEL', 'Airtel')], max_length=10)),
                ('amount', models.DecimalField(decimal_places=2, help_text='Medicine/item amount entered by customer, before fees.', max_digits=12, validators=[django.core.validators.MinValueValidator(Decimal('1'))])),
                ('mm_fee', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=10)),
                ('edoctor_commission', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=10)),
                ('total_payable', models.DecimalField(decimal_places=2, max_digits=12)),
                ('currency', models.CharField(default='UGX', max_length=3)),
                ('status', models.CharField(choices=[('PENDING', 'Pending'), ('SUCCESS', 'Success'), ('FAILED', 'Failed'), ('CANCELLED', 'Cancelled')], default='PENDING', max_length=10)),
                ('payment_confirmation_reference', models.CharField(blank=True, max_length=64, null=True)),
                ('settlement_status', models.CharField(choices=[('PENDING', 'Pending'), ('SETTLED', 'Settled'), ('FAILED', 'Failed')], default='PENDING', max_length=15)),
                ('raw_callout_request', dashboard.models.JSONTextField(blank=True, help_text='Raw mobile-money callout request stored as JSON text.', null=True)),
                ('raw_ipn_payload', dashboard.models.JSONTextField(blank=True, help_text='Raw IPN payload stored as JSON text.', null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('provider', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='transactions', to='dashboard.provider')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='IPNLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('direction', models.CharField(choices=[('SUCCESS', 'Success'), ('FAILURE', 'Failure')], max_length=10)),
                ('payload', dashboard.models.JSONTextField(help_text='Raw IPN payload stored as JSON text.')),
                ('received_at', models.DateTimeField(auto_now_add=True)),
                ('transaction', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='ipn_logs', to='dashboard.transaction')),
            ],
            options={
                'ordering': ['-received_at'],
            },
        ),
        migrations.AddIndex(
            model_name='transaction',
            index=models.Index(fields=['status'], name='dashboard_t_status_7b0a67_idx'),
        ),
        migrations.AddIndex(
            model_name='transaction',
            index=models.Index(fields=['network'], name='dashboard_t_network_6fd80e_idx'),
        ),
        migrations.AddIndex(
            model_name='transaction',
            index=models.Index(fields=['created_at'], name='dashboard_t_created_ac801e_idx'),
        ),
    ]
